networks:
  minha_net:

services:
  postgres_db:
    build: 
      context: ./src/db
      dockerfile: db.Dockerfile
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: meubanco
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - minha_net
    ports:
      - "5432:5432"

  backend:
    build: 
      context: ./src/back
      dockerfile: back.Dockerfile
    container_name: backend
    environment:
      DB_HOST: postgres_db
      DB_NAME: meubanco
      DB_USER: admin
      DB_PASS: admin
    depends_on:
      - postgres_db
    networks:
      - minha_net
    ports:
      - "5000:5000"

  frontend:
    build: 
      context: ./src/front
      dockerfile: front.Dockerfile
    container_name: frontend
    depends_on:
      - backend
    networks:
      - minha_net
    ports:
      - "8080:8080"

volumes:
  pgdata:

